version: '3.8'

x-services-volume:
  &services-volume
  type: bind
  source: ./appdata
  target: /var/appdata
  
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GIT_SSL_NO_VERIFY=true
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - GIT_SSL_NO_VERIFY=true
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDETfGzA4XH/ha1g9O/XgqCDrIfDRXzwJmgah5DkmahUoITV5aBH5koB+aeCtozppipHwqu+qxMoFN9OVFFa/6wuZUxjcVIZF+hW/Opzr/6RsSglEXm9L/Dz1AdsnATf3XHjF4Grv9hv1n5ldSZV4cY5F1uqskcFIT5OK0m+e+CBRRzeXYjoXED67MPGaL3fsPL3zo6KZd70q+FxSfMuTrDFW9mZNHTbldF8gxiyS7+8leCLGnlqkZcWT8+EPC6G8qi4W/dKjmse3zq8NCC2iLb2Zk4dF1lA0ImCQGrfGwbCwyAFez23vIXyiI3UMGNXOdz4yIcGJ/STkQPhOKdXaNI8vPs4V5cITjgVIACJOS1D7/OSNaL9JUqBu86BRXwiE6H8I/7Xk0XjL3oi/iyShuKyb2RzVrFBdQoDpyziCJ0Pi2D2MCdxA9/EZy2HJMNDXknErf0TFsaL/+ZN5vM6Rr/qggON/mSO334FkinBlgbsJh4Q9LarfuWFjMYnepiSbc= jenkins@8fab23d94242
    volumes: 
      - *services-volume
  opencv:
    image: sixsq/opencv-python:latest
    privileged: true
    user: root
    container_name: opencv
    volumes: 
      - *services-volume
    tty: true
