#!/bin/bash
#sudo apt install -y openssh-server
# on computer vision PC

#install docker compose
#insted https://docs.docker.com/engine/install/ubuntu/
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
sudo usermod -aG docker $USER
sudo apt  install -y docker-compose 

#download repo application + platform
git clone https://github.com/trendy-automation/plc_cv plc_cv

# copy application to docker volume
cd plc_cv
cp -ir python docker-compose/appdata/python
cd docker-compose


# docker compose up
sudo docker-compose up --build -d

#sudo docker-compose exec jenkins cat var/jenkins_home/secrets/initialAdminPassword


#info camers docker
# https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device
# https://medium.com/@jijupax/connect-the-webcam-to-docker-on-mac-or-windows-51d894c44468
# https://hub.docker.com/r/lmwafer/realsense-ready
# https://stackoverflow.com/questions/33985648/access-camera-inside-docker-container
# jenkins install by ansible
# https://habr.com/ru/articles/680170/


sudo ip link set wlan0 up
sudo iw dev wlan0 link
sudo iwctl station wlan0 scan
sudo ifconfig wlan0 up
nmcli d wifi list
iwconfig
iwlist scan | more

#https://unix.stackexchange.com/questions/450501/unable-to-connect-to-wlan0-via-wpa-supplicant