version: 1.0
logger:
  level: INFO
  debug_file: 'debug.log'
  format: '%(asctime)-15s %(name)s %(message)s'
plc:
  ip: 192.168.0.10
  camera_db_num: 8
  part_type_byte: 1
  part_posnum_byte: 2
  vision_mode_byte: 4
  reconnect_timeout: 60
vision:
  capture:
    scaleAbs_alpha: 0.3
  pipline:
      # resolution_x, resolution_y :  640, 480 | 848, 480 | 1280,720
      resolution_x: 848
      resolution_y: 480
      # fps :  5 | 15 | 30 | 60
      fps: 5
  match_template:
    template_dir: 'templates'
    limits:
      match_threshold: 0.95
      delta_angle: 5
      delta_scale: 0
      offset_pix: 30
    save_history: on
  stream:
    quality: 100
parts: 
  - code: '8АТ-1250-11'
    part_name: 'Корпус маятника'
    step_name: 'Установ А'
    height: 212
    width: 89
    type: 1
  - code: '8АТ-1250-11'
    part_name: 'Корпус маятника'
    step_name: 'Установ B'
    height: 208
    width: 87
    type: 2
  - code: '8АТ-1250-11'
    part_name: 'Корпус маятника'
    step_name: 'Установ C'
    height: 208
    width: 80.6
    type: 3
  - code: '8АТ-1250-11'
    part_name: 'Корпус маятника'
    step_name: 'Установ D'
    height: 208
    width: 80
    type: 4
  - code: '8АТ-1250-11'
    part_name: 'Корпус маятника'
    step_name: 'Установ E'
    height: 528
    width: 268
    type: 5
  - code: '17115.2900.77'
    part_name: 'Переходник'
    step_name: 'Установ А'
    height: 273
    width: 206
    type: 6
  - code: '17115.2900.77'
    part_name: 'Переходник'
    step_name: 'Установ B'
    height: 209.03
    width: 206
    type: 7
