version: 1.0
logger:
  level: INFO
  debug_file: 'debug.log'
  format: '%(asctime)-15s %(name)s %(message)s'
plc:
  ip: 192.168.0.10
  camera_db_num: 8
  reconnect_timeout: 60
vision:
  scaleAbs_alpha: 0.3
  templateThreshold: 0.85
  maxShiftPix: 30
  templateDir: 'templates'
  configStream:
      resolution_x: 848
      resolution_y: 480
      fps: 5
