version: 1.0
logger:
  level: logging.INFO
  handlers: [logging.StreamHandler(sys.stdout),
             logging.handlers.RotatingFileHandler
              ("./debug.log", maxBytes=(1048576 * 5), backupCount=7)]
  format: '%(asctime)-15s %(name)s %(message)s'
plc_ip: 192.168.0.10